apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: server-serviceentry
spec:
  hosts:
  - server-0.server.default.svc.cluster.local
  - server-1.server.default.svc.cluster.local
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: DNS
